version: "3.9"

services:
  jupyter:
    image: "tensorflow/tensorflow:latest-gpu-jupyter"
    volumes:
      - type: bind
        source: .
        target: /tf
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu